theme = "hook"

base_url = "https://raunakab.github.io"
compile_sass = true
build_search_index = false

title = "@rabh"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[[extra.links]]
title = "GitHub"
href = "https://github.com/raunakab"

[[extra.links]]
title = "LinkedIn"
href = "https://www.linkedin.com/in/raunakbhagat"

[[extra.links]]
title = "Resume (PDF download)"
href = "https://github.com/raunakab/resume/releases/download/1.0.0-2024.04.30/rb-resume.pdf"

[[extra.links]]
title = "Resume (GitHub releases)"
href = "https://github.com/raunakab/resume/releases/tag/1.0.0-2024.04.30"

[[extra.links]]
title = "Mail"
href = "mailto:rabhagat31@gmail.com"
