theme = "hook"

base_url = "https://raunakab.github.io"
compile_sass = true
build_search_index = false

title = "@rabh"
description = "Description"
highlight_code = true
highlight_theme = "agola-dark"

[[extra.links]]
title = "GitHub"
href = "https://github.com/raunakab"

[[extra.links]]
title = "LinkedIn"
href = "https://www.linkedin.com/in/raunakbhagat"

[[extra.links]]
title = "Resume"
href = "https://github.com/raunakab/resume/releases/tag/1.0.0-2024.04.30"

[[extra.links]]
title = "Mail"
href = "mailto:rabhagat31@gmail.com"
