theme = "lightspeed"
base_url = "https://raunakab.github.io"
compile_sass = true
build_search_index = true

title = "@rabh"
description = "Personal blog"

[[extra.footer_links]]
url = "$BASE_URL/about"
name = "About"
