# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.14.1
        with:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.TOKEN }}

# on: push
# name: Build and deploy GH Pages
# jobs:
#   build:
#     name: shalzz/zola-deploy-action
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
#     - name: shalzz/zola-deploy-action
#       uses: shalzz/zola-deploy-action@master
#       env:
#         PAGES_BRANCH: gh-pages
#         TOKEN: ${{ secrets.TOKEN }}
#         ZOLA_ENV: prod

# On every push this script is executed
# on: push
# name: Build and deploy GH Pages
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     steps:
#       - name: checkout
#         uses: actions/checkout@v2
#       - name: build_and_deploy
#         uses: shalzz/zola-deploy-action@v0.14.1
#         env:
#           # Target branch
#           PAGES_BRANCH: gh-pages
#           # Provide personal access token
#           TOKEN: ${{ secrets.TOKEN }}
#           ZOLA_ENV: prod
