name: Zola on GitHub Pages
on: 
 push:
  branches:
   - master

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v3.0.0
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# # On every push this script is executed
# on: push
# name: Build and deploy GH Pages
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/master'
#     steps:
#       - name: checkout
#         uses: actions/checkout@v2
#       - name: build_and_deploy
#         uses: shalzz/zola-deploy-action@v0.15.3
#         env:
#           # Target branch
#           PAGES_BRANCH: master
#           # Provide personal access token
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           # TOKEN: ${{ secrets.TOKEN }}

# # # # On every push this script is executed
# # # on: push
# # # name: Build and deploy GH Pages
# # # jobs:
# # #   build:
# # #     runs-on: ubuntu-latest
# # #     if: github.ref == 'refs/heads/master'
# # #     steps:
# # #       - name: checkout
# # #         uses: actions/checkout@v2
# # #       - name: build_and_deploy
# # #         uses: shalzz/zola-deploy-action@v0.14.1
# # #         with:
# # #           PAGES_BRANCH: gh-pages
# # #           TOKEN: ${{ secrets.TOKEN }}
# # #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# # on: push
# # name: Build and deploy GH Pages
# # jobs:
# #   build:
# #     name: shalzz/zola-deploy-action
# #     runs-on: ubuntu-latest
# #     steps:
# #     - uses: actions/checkout@master
# #     - name: shalzz/zola-deploy-action
# #       uses: shalzz/zola-deploy-action@master
# #       with:
# #         PAGES_BRANCH: gh-pages
# #         TOKEN: ${{ secrets.TOKEN }}
# #         ZOLA_ENV: prod

# # # On every push this script is executed
# # # on: push
# # # name: Build and deploy GH Pages
# # # jobs:
# # #   build:
# # #     runs-on: ubuntu-latest
# # #     if: github.ref == 'refs/heads/main'
# # #     steps:
# # #       - name: checkout
# # #         uses: actions/checkout@v2
# # #       - name: build_and_deploy
# # #         uses: shalzz/zola-deploy-action@v0.14.1
# # #         env:
# # #           # Target branch
# # #           PAGES_BRANCH: gh-pages
# # #           # Provide personal access token
# # #           TOKEN: ${{ secrets.TOKEN }}
# # #           ZOLA_ENV: prod
