name: Build and deploy Zola website on GitHub Pages

on: 
 push:
  branches:
   - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v4
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.18.0
      env:
        PAGES_BRANCH: gh-pages-deployment
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
